# This file is used for Gemika (https://github.com/makandra/gemika) only.
# It will not work with travis-ci.

language: ruby

rvm:
  - 2.4.5
  - 2.6.6

matrix:
  include:
    # Test projects
    - gemfile: tests/rails-4_capybara-2/Gemfile
      rvm: 2.4.5
    - gemfile: tests/rails-6_capybara-3/Gemfile
      rvm: 2.6.6
    # Used to run rspec and tests for spreewald binary:
    - gemfile: Gemfile.ruby245
      rvm: 2.4.5
    - gemfile: Gemfile.ruby266
      rvm: 2.6.6

